import { drizzle } from "drizzle-orm/mysql2";
import * as schema from "./drizzle/schema.js";

const db = drizzle(process.env.DATABASE_URL);

async function seed() {
  console.log("🌱 Seeding database with Chula Vista data...");

  // Seed restaurants
  const restaurants = [
    // Mexican Cuisine
    {
      nameEn: "Tacos El Gordo",
      nameEs: "Tacos El Gordo",
      cuisine: "mexican",
      neighborhood: "downtown",
      address: "689 E St, Chula Vista, CA 91910",
      latitude: "32.6279",
      longitude: "-117.0814",
      descriptionEn: "Tijuana-style tacos, award-winning and very popular",
      descriptionEs: "Tacos estilo Tijuana, galardonados y muy populares",
      phone: "(619) 691-8848",
      familyFriendly: 1,
      priceRange: "$",
      rating: "4.5",
      hoursEn: "Mon-Sun: 9:00 AM - 2:00 AM",
      hoursEs: "Lun-Dom: 9:00 AM - 2:00 AM",
    },
    {
      nameEn: "Talavera Azul",
      nameEs: "Talavera Azul",
      cuisine: "mexican",
      neighborhood: "third_avenue",
      address: "320 Third Ave, Chula Vista, CA 91910",
      latitude: "32.6275",
      longitude: "-117.0842",
      descriptionEn: "Featured on Food Network, authentic Mexican cuisine",
      descriptionEs: "Destacado en Food Network, cocina mexicana auténtica",
      phone: "(619) 585-0610",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.6",
      hoursEn: "Tue-Sun: 11:00 AM - 9:00 PM",
      hoursEs: "Mar-Dom: 11:00 AM - 9:00 PM",
    },
    {
      nameEn: "El Patio Restaurant",
      nameEs: "El Patio Restaurant",
      cuisine: "mexican",
      neighborhood: "downtown",
      address: "568 Broadway, Chula Vista, CA 91910",
      latitude: "32.6268",
      longitude: "-117.0845",
      descriptionEn: "Family-owned for 67+ years, authentic Mexican cuisine",
      descriptionEs: "Familiar por más de 67 años, cocina mexicana auténtica",
      phone: "(619) 427-3611",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.4",
      hoursEn: "Mon-Sun: 8:00 AM - 9:00 PM",
      hoursEs: "Lun-Dom: 8:00 AM - 9:00 PM",
    },
    {
      nameEn: "Tacos El Prieto",
      nameEs: "Tacos El Prieto",
      cuisine: "mexican",
      neighborhood: "third_avenue",
      address: "Main Street, Chula Vista, CA 91910",
      latitude: "32.6280",
      longitude: "-117.0825",
      descriptionEn: "Traditional tacos on Main Street",
      descriptionEs: "Tacos tradicionales en Main Street",
      familyFriendly: 1,
      priceRange: "$",
      rating: "4.3",
      hoursEn: "Mon-Sun: 9:00 AM - 10:00 PM",
      hoursEs: "Lun-Dom: 9:00 AM - 10:00 PM",
    },
    // Asian Cuisine
    {
      nameEn: "Luscious Dumplings",
      nameEs: "Luscious Dumplings",
      cuisine: "asian",
      neighborhood: "eastlake",
      address: "1015 Eastlake Pkwy, Chula Vista, CA 91915",
      latitude: "32.6385",
      longitude: "-117.0625",
      descriptionEn: "Chinese dumplings and authentic cuisine",
      descriptionEs: "Dumplings chinos y cocina auténtica",
      phone: "(619) 656-8899",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.7",
      hoursEn: "Mon-Sun: 11:00 AM - 9:00 PM",
      hoursEs: "Lun-Dom: 11:00 AM - 9:00 PM",
    },
    {
      nameEn: "Banh Mi Paris Express",
      nameEs: "Banh Mi Paris Express",
      cuisine: "asian",
      neighborhood: "downtown",
      address: "Third Ave, Chula Vista, CA 91910",
      latitude: "32.6272",
      longitude: "-117.0838",
      descriptionEn: "Vietnamese cuisine and banh mi sandwiches",
      descriptionEs: "Cocina vietnamita y sándwiches banh mi",
      familyFriendly: 1,
      priceRange: "$",
      rating: "4.6",
      hoursEn: "Mon-Sat: 9:00 AM - 7:00 PM",
      hoursEs: "Lun-Sáb: 9:00 AM - 7:00 PM",
    },
    {
      nameEn: "Phology Noodle House",
      nameEs: "Phology Noodle House",
      cuisine: "asian",
      neighborhood: "eastlake",
      address: "Eastlake Pkwy, Chula Vista, CA 91915",
      latitude: "32.6390",
      longitude: "-117.0630",
      descriptionEn: "Asian noodles and pho",
      descriptionEs: "Fideos asiáticos y pho",
      phone: "(619) 656-3388",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.4",
      hoursEn: "Mon-Sun: 11:00 AM - 9:00 PM",
      hoursEs: "Lun-Dom: 11:00 AM - 9:00 PM",
    },
    {
      nameEn: "Okayama Steakhouse",
      nameEs: "Okayama Steakhouse",
      cuisine: "asian",
      neighborhood: "eastlake",
      address: "1480 Eastlake Pkwy, Ste 901, Chula Vista, CA 91915",
      latitude: "32.6392",
      longitude: "-117.0628",
      descriptionEn: "Japanese steakhouse with teppanyaki",
      descriptionEs: "Steakhouse japonés con teppanyaki",
      phone: "(858) 294-3042",
      familyFriendly: 1,
      priceRange: "$$$",
      rating: "4.5",
      hoursEn: "Mon-Sun: 5:00 PM - 10:00 PM",
      hoursEs: "Lun-Dom: 5:00 PM - 10:00 PM",
    },
    {
      nameEn: "Sushi House",
      nameEs: "Sushi House",
      cuisine: "asian",
      neighborhood: "downtown",
      address: "Downtown Chula Vista, CA 91910",
      latitude: "32.6270",
      longitude: "-117.0840",
      descriptionEn: "Fresh sushi and Japanese cuisine",
      descriptionEs: "Sushi fresco y cocina japonesa",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.5",
      hoursEn: "Tue-Sun: 11:30 AM - 9:00 PM",
      hoursEs: "Mar-Dom: 11:30 AM - 9:00 PM",
    },
    // Italian Cuisine
    {
      nameEn: "Italianissimo Trattoria",
      nameEs: "Italianissimo Trattoria",
      cuisine: "italian",
      neighborhood: "downtown",
      address: "Downtown Chula Vista, CA 91910",
      latitude: "32.6273",
      longitude: "-117.0843",
      descriptionEn: "Authentic Italian trattoria",
      descriptionEs: "Trattoria italiana auténtica",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.6",
      hoursEn: "Tue-Sun: 5:00 PM - 10:00 PM",
      hoursEs: "Mar-Dom: 5:00 PM - 10:00 PM",
    },
    {
      nameEn: "Savoie Italian Eatery",
      nameEs: "Savoie Italian Eatery",
      cuisine: "italian",
      neighborhood: "otay_ranch",
      address: "Otay Ranch, Chula Vista, CA 91914",
      latitude: "32.5850",
      longitude: "-116.9750",
      descriptionEn: "Excellent Italian food with great service",
      descriptionEs: "Excelente comida italiana con gran servicio",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.7",
      hoursEn: "Mon-Sun: 11:00 AM - 10:00 PM",
      hoursEs: "Lun-Dom: 11:00 AM - 10:00 PM",
    },
    // American Cuisine
    {
      nameEn: "Yard House",
      nameEs: "Yard House",
      cuisine: "american",
      neighborhood: "eastlake",
      address: "2015 Birch Rd, Ste 803, Chula Vista, CA 91915",
      latitude: "32.6395",
      longitude: "-117.0632",
      descriptionEn: "American gastropub with extensive beer selection",
      descriptionEs: "Gastropub americano con amplia selección de cervezas",
      phone: "(619) 656-2400",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.4",
      hoursEn: "Mon-Sun: 11:00 AM - 11:00 PM",
      hoursEs: "Lun-Dom: 11:00 AM - 11:00 PM",
    },
    {
      nameEn: "Aunt Emma's Pancakes",
      nameEs: "Aunt Emma's Pancakes",
      cuisine: "american",
      neighborhood: "downtown",
      address: "Downtown Chula Vista, CA 91910",
      latitude: "32.6276",
      longitude: "-117.0841",
      descriptionEn: "Breakfast and brunch spot",
      descriptionEs: "Lugar de desayuno y brunch",
      familyFriendly: 1,
      priceRange: "$",
      rating: "4.5",
      hoursEn: "Mon-Sun: 7:00 AM - 2:00 PM",
      hoursEs: "Lun-Dom: 7:00 AM - 2:00 PM",
    },
    {
      nameEn: "Farmer's Table",
      nameEs: "Farmer's Table",
      cuisine: "american",
      neighborhood: "downtown",
      address: "Downtown Chula Vista, CA 91910",
      latitude: "32.6274",
      longitude: "-117.0839",
      descriptionEn: "Farm-to-table fresh cuisine",
      descriptionEs: "Cocina fresca de la granja a la mesa",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.6",
      hoursEn: "Mon-Sun: 8:00 AM - 9:00 PM",
      hoursEs: "Lun-Dom: 8:00 AM - 9:00 PM",
    },
    // Seafood
    {
      nameEn: "La Pesca Cevicheria Baja",
      nameEs: "La Pesca Cevicheria Baja",
      cuisine: "seafood",
      neighborhood: "downtown",
      address: "Third Ave, Chula Vista, CA 91910",
      latitude: "32.6271",
      longitude: "-117.0837",
      descriptionEn: "Baja California-style ceviche",
      descriptionEs: "Ceviche estilo Baja California",
      familyFriendly: 1,
      priceRange: "$$",
      rating: "4.7",
      hoursEn: "Tue-Sun: 11:00 AM - 8:00 PM",
      hoursEs: "Mar-Dom: 11:00 AM - 8:00 PM",
    },
    // Brewery
    {
      nameEn: "Novo Brazil Brewing",
      nameEs: "Novo Brazil Brewing",
      cuisine: "brewery",
      neighborhood: "third_avenue",
      address: "Third Avenue, Chula Vista, CA 91910",
      latitude: "32.6277",
      longitude: "-117.0836",
      descriptionEn: "Craft brewery with Brazilian-inspired beers",
      descriptionEs: "Cervecería artesanal con cervezas de inspiración brasileña",
      familyFriendly: 0,
      priceRange: "$$",
      rating: "4.5",
      hoursEn: "Wed-Sun: 3:00 PM - 10:00 PM",
      hoursEs: "Mié-Dom: 3:00 PM - 10:00 PM",
    },
  ];

  console.log(`Inserting ${restaurants.length} restaurants...`);
  await db.insert(schema.restaurants).values(restaurants);

  // Seed events
  const events = [
    {
      titleEn: "Saturday Sketching",
      titleEs: "Dibujo de Sábado",
      descriptionEn: "Join us for a community sketching session at the library",
      descriptionEs: "Únete a nosotros para una sesión de dibujo comunitario en la biblioteca",
      startDate: new Date("2026-02-21T11:00:00"),
      endDate: new Date("2026-02-21T12:30:00"),
      location: "Civic Center Library",
      address: "365 F St, Chula Vista, CA 91910",
      latitude: "32.6279",
      longitude: "-117.0842",
      category: "arts",
      isFree: 1,
    },
    {
      titleEn: "Toddler Storytime",
      titleEs: "Hora del Cuento para Niños Pequeños",
      descriptionEn: "Interactive storytime for toddlers and their families",
      descriptionEs: "Hora del cuento interactiva para niños pequeños y sus familias",
      startDate: new Date("2026-02-18T10:00:00"),
      endDate: new Date("2026-02-18T10:45:00"),
      location: "Civic Center Library",
      address: "365 F St, Chula Vista, CA 91910",
      latitude: "32.6279",
      longitude: "-117.0842",
      category: "family",
      isFree: 1,
    },
    {
      titleEn: "Art Supplies Swap",
      titleEs: "Intercambio de Materiales de Arte",
      descriptionEn: "Exchange art supplies with fellow artists in the community",
      descriptionEs: "Intercambia materiales de arte con otros artistas de la comunidad",
      startDate: new Date("2026-02-25T13:30:00"),
      endDate: new Date("2026-02-25T15:00:00"),
      location: "Otay Recreation Center",
      address: "3554 Main St, Chula Vista, CA 91911",
      latitude: "32.6285",
      longitude: "-117.0820",
      category: "arts",
      isFree: 1,
    },
    {
      titleEn: "Lovebugs: Story & Crafts",
      titleEs: "Lovebugs: Cuento y Manualidades",
      descriptionEn: "Valentine's themed story and craft session for kids",
      descriptionEs: "Sesión de cuento y manualidades con tema de San Valentín para niños",
      startDate: new Date("2026-02-18T13:30:00"),
      endDate: new Date("2026-02-18T14:15:00"),
      location: "Civic Center Library",
      address: "365 F St, Chula Vista, CA 91910",
      latitude: "32.6279",
      longitude: "-117.0842",
      category: "family",
      isFree: 1,
    },
    {
      titleEn: "Third Avenue Art Walk",
      titleEs: "Paseo de Arte en Third Avenue",
      descriptionEn: "Monthly art walk featuring local artists and galleries",
      descriptionEs: "Paseo de arte mensual con artistas locales y galerías",
      startDate: new Date("2026-03-07T17:00:00"),
      endDate: new Date("2026-03-07T21:00:00"),
      location: "Third Avenue District",
      address: "Third Avenue, Chula Vista, CA 91910",
      latitude: "32.6275",
      longitude: "-117.0840",
      category: "arts",
      isFree: 1,
    },
  ];

  console.log(`Inserting ${events.length} events...`);
  await db.insert(schema.events).values(events);

  // Seed curated experiences
  const experiences = [
    {
      titleEn: "Unexpected Date Night",
      titleEs: "Cita Nocturna Inesperada",
      descriptionEn:
        "Start with craft cocktails at a hidden bar, enjoy authentic Mexican cuisine, and end with a romantic bayfront sunset walk.",
      descriptionEs:
        "Comienza con cócteles artesanales en un bar escondido, disfruta de auténtica cocina mexicana y termina con un romántico paseo al atardecer en la bahía.",
      slug: "unexpected-date-night",
      duration: "3-4 hours",
      parkingTipsEn: "Street parking available on Third Avenue. Bayfront has free parking after 6 PM.",
      parkingTipsEs: "Estacionamiento en la calle disponible en Third Avenue. Bayfront tiene estacionamiento gratuito después de las 6 PM.",
      bestTime: "Friday or Saturday evening",
    },
    {
      titleEn: "Perfect Family Saturday",
      titleEs: "Sábado Familiar Perfecto",
      descriptionEn:
        "Morning at Living Coast Discovery Center, lunch at a family-friendly restaurant, and afternoon at Chula Vista Bayfront Park.",
      descriptionEs:
        "Mañana en Living Coast Discovery Center, almuerzo en un restaurante familiar y tarde en Chula Vista Bayfront Park.",
      slug: "perfect-family-saturday",
      duration: "Full day",
      parkingTipsEn: "Free parking at Living Coast and Bayfront Park. Arrive early on weekends.",
      parkingTipsEs: "Estacionamiento gratuito en Living Coast y Bayfront Park. Llega temprano los fines de semana.",
      bestTime: "Saturday morning",
    },
    {
      titleEn: "Bayfront Sunset + Dinner",
      titleEs: "Atardecer en la Bahía + Cena",
      descriptionEn:
        "Watch the sunset at Chula Vista Bayfront, then enjoy dinner at a waterfront restaurant with bay views.",
      descriptionEs:
        "Observa el atardecer en Chula Vista Bayfront, luego disfruta de una cena en un restaurante frente al mar con vistas a la bahía.",
      slug: "bayfront-sunset-dinner",
      duration: "2-3 hours",
      parkingTipsEn: "Free parking at Bayfront Park. Restaurant has valet parking available.",
      parkingTipsEs: "Estacionamiento gratuito en Bayfront Park. El restaurante tiene servicio de valet disponible.",
      bestTime: "Any evening",
    },
    {
      titleEn: "Craft Beer & Live Music",
      titleEs: "Cerveza Artesanal y Música en Vivo",
      descriptionEn:
        "Tour local breweries on Third Avenue, enjoy craft beers, and catch live music at a local venue.",
      descriptionEs:
        "Recorre las cervecerías locales en Third Avenue, disfruta de cervezas artesanales y escucha música en vivo en un lugar local.",
      slug: "craft-beer-live-music",
      duration: "3-4 hours",
      parkingTipsEn: "Street parking on Third Avenue. Consider ride-sharing for safety.",
      parkingTipsEs: "Estacionamiento en la calle en Third Avenue. Considera usar transporte compartido por seguridad.",
      bestTime: "Friday or Saturday evening",
    },
  ];

  console.log(`Inserting ${experiences.length} curated experiences...`);
  await db.insert(schema.curatedExperiences).values(experiences);

  // Seed amenities
  const amenities = [
    {
      nameEn: "Chula Vista Bayfront Park",
      nameEs: "Parque Chula Vista Bayfront",
      category: "parks",
      descriptionEn:
        "Beautiful waterfront park with picnic areas, boat launch, and stunning bay views. Perfect for families and outdoor activities.",
      descriptionEs:
        "Hermoso parque frente al mar con áreas de picnic, rampa para botes y vistas impresionantes de la bahía. Perfecto para familias y actividades al aire libre.",
      address: "999 Sandpiper Way, Chula Vista, CA 91910",
      latitude: "32.6000",
      longitude: "-117.0900",
      website: "https://www.portofsandiego.org/chula-vista-bayfront-park",
    },
    {
      nameEn: "Living Coast Discovery Center",
      nameEs: "Living Coast Discovery Center",
      category: "nature_center",
      descriptionEn:
        "Interactive nature center featuring local wildlife, birds, and marine animals. Educational and fun for all ages.",
      descriptionEs:
        "Centro de naturaleza interactivo con vida silvestre local, aves y animales marinos. Educativo y divertido para todas las edades.",
      address: "1000 Gunpowder Point Dr, Chula Vista, CA 91910",
      latitude: "32.6050",
      longitude: "-117.0950",
      website: "https://www.thelivingcoast.org",
    },
    {
      nameEn: "Chula Vista Water Sports",
      nameEs: "Deportes Acuáticos Chula Vista",
      category: "water_sports",
      descriptionEn: "Kayaking, paddleboarding, and water sports rentals at the Chula Vista Marina.",
      descriptionEs: "Kayak, paddleboard y alquiler de deportes acuáticos en la Marina de Chula Vista.",
      address: "Chula Vista Marina, Chula Vista, CA 91910",
      latitude: "32.6020",
      longitude: "-117.0920",
    },
    {
      nameEn: "Chula Vista Trails Network",
      nameEs: "Red de Senderos de Chula Vista",
      category: "trails",
      descriptionEn:
        "Over 120 miles of bike paths, lanes, and trails throughout Chula Vista for walking, hiking, jogging, and biking.",
      descriptionEs:
        "Más de 120 millas de senderos para bicicletas, carriles y rutas en toda Chula Vista para caminar, hacer senderismo, trotar y andar en bicicleta.",
      address: "Various locations throughout Chula Vista",
      latitude: "32.6401",
      longitude: "-117.0842",
    },
  ];

  console.log(`Inserting ${amenities.length} amenities...`);
  await db.insert(schema.amenities).values(amenities);

  console.log("✅ Database seeded successfully!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("❌ Error seeding database:", error);
  process.exit(1);
});
